name: Sales Analytics Pipeline

on:

  workflow_dispatch:

  schedule:
    - cron: '0 9 * * *'

# ==========================================
# IMPORTANT PERMISSION FIX
# ==========================================

permissions:
  contents: write

jobs:

  analytics-job:

    runs-on: ubuntu-latest

    steps:

      # ==========================================
      # CHECKOUT REPOSITORY
      # ==========================================

      - name: Checkout Repository
        uses: actions/checkout@v4

        with:
            persist-credentials: true

      # ==========================================
      # SETUP PYTHON
      # ==========================================

      - name: Setup Python
        uses: actions/setup-python@v5

        with:
          python-version: '3.11'

      # ==========================================
      # INSTALL DEPENDENCIES
      # ==========================================

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      # ==========================================
      # RUN ANALYTICS PIPELINE
      # ==========================================

      - name: Execute Analytics Pipeline
        run: |
          python main.py

      # ==========================================
      # COMMIT REPORTS
      # ==========================================

      - name: Commit Reports

        run: |

          git config --global user.name "github-actions"

          git config --global user.email "actions@github.com"

          git add .

          git commit -m "Automated analytics update" || echo "No changes"

          git push